/* Generated by CMake build scripts, manual changes will be lost */

#ifndef __CONFIG_H__
#define __CONFIG_H__

#define PACKAGE "icewm"
#define PACKAGE_NAME "icewm"
#define PACKAGE_TARNAME "icewm"
#define PACKAGE_VERSION "1.3.12+mod+20170325.1"
#define PACKAGE_STRING "icewm 1.3.12+mod+20170325.1"
#define PACKAGE_URL ""
#define VERSION "1.3.12+mod+20170325.1"

#define HOSTCPU "x86_64"
#define HOSTOS "Linux"

// autoconf declares them but I couldn't find any good reason to use them. Wiping out...
#define SELECT_TYPE_ARG1
#define SELECT_TYPE_ARG234
#define SELECT_TYPE_ARG5

#define SIZEOF_CHAR 1
#define SIZEOF_INT 4
#define SIZEOF_LONG 8
#define SIZEOF_SHORT 2

#define HAVE_DUP2
#define HAVE_GETCWD
#define HAVE_GETHOSTBYNAME
#define HAVE_GETHOSTNAME
#define HAVE_GETTIMEOFDAY
#define HAVE_MBLEN
#define HAVE_MEMCHR
#define HAVE_MEMMOVE
#define HAVE_MEMSET
#define HAVE_MKDIR
#define HAVE_NL_LANGINFO
#define HAVE_PUTENV
#define HAVE_SELECT
#define HAVE_SETLOCALE
#define HAVE_SOCKET
#define HAVE_STRCASECMP
#define HAVE_STRCHR
#define HAVE_STRCSPN
#define HAVE_STRDUP
#define HAVE_STRERROR
#define HAVE_STRNCASECMP
#define HAVE_STRRCHR
#define HAVE_STRSPN
#define HAVE_STRSTR
#define HAVE_STRTOL
#define HAVE_SYSINFO
#define HAVE_UNAME
#define HAVE_ABORT
#define HAVE_GETTIMEOFDAY
#define HAVE_PUTENV
#define HAVE_SELECT
#define HAVE_SOCKET
#define HAVE_STRTOL
#define HAVE_BASENAME
/* #undef HAVE_SYSCTLBYNAME */
#define HAVE_GETLOADAVG

#define HAVE_FCNTL_H
#define HAVE_LANGINFO_H
#define HAVE_LIBINTL_H
#define HAVE_LIMITS_H
#define HAVE_LOCALE_H
#define HAVE_NETDB_H
#define HAVE_NETINET_IN_H
#define HAVE_STDDEF_H
#define HAVE_STDLIB_H
#define HAVE_STRING_H
#define HAVE_SYS_FILE_H
#define HAVE_SYS_IOCTL_H
#define HAVE_SYS_PARAM_H
#define HAVE_SYS_SOCKET_H
#define HAVE_SYS_TIME_H
#define HAVE_UNISTD_H
#define HAVE_WCHAR_H
#define HAVE_SCHED_H
/* #undef HAVE_SYS_DKSTAT_H */
#define HAVE_SYS_PARAM_H
#define HAVE_SYS_SYSCTL_H
/* #undef HAVE_UVM_UVM_PARAM_H */
#define HAVE_LIBGEN_H
/* #undef HAVE_MACHINE_APMVAR_H */
/* #undef HAVE_MACHINE_APM_BIOS_H */
#define HAVE_EXECINFO_H
#define HAVE_ASPRINTF

#define LIBDIR "/usr/share/icewm"
#define CFGDIR "/etc/X11/icewm"
#define DOCDIR "/usr/share/doc/icewm-common"
#define LOCDIR "/usr/share/locale"
#define DATADIR "/usr/share"
#define ICEHELPIDX "/usr/share/doc/icewm-common/html/icewm.html"

/* #undef NO_CONFIGURE_MENUES */
/* #undef CONFIG_XPM */
/* #undef CONFIG_IMLIB */
#define CONFIG_GDK_PIXBUF_XLIB
#define CONFIG_I18N
#define ENABLE_NLS
#define CONFIG_SESSION
#define CONFIG_SHAPE
#define CONFIG_SHAPED_DECORATION

/* #undef CONFIG_UNICODE_SET */

#define HAVE_XINTERNATOMS


#define CONFIG_ANTIALIASING
#define CONFIG_GRADIENTS
/* #undef CONFIG_XRANDR */

/* #undef CONFIG_XFREETYPE */

#define CONFIG_COREFONTS
/* #undef CONFIG_PDA */

/* #undef CONFIG_GUIEVENTS */
/* #undef CONFIG_OSS */
/* #undef ENABLE_ALSA */
/* #undef ENABLE_YIFF */
/* #undef ENABLE_ESD */
#define XINERAMA
/* #undef CONFIG_FRIBIDI */

/* #undef NO_CONFIGURE */
/* #undef NO_KEYBIND */
/* #undef NO_CONFIGURE_MENUS */
/* #undef NO_WINDOW_OPTIONS */
#define LITE
/* #undef CONFIG_TOOLTIP */
/* #undef CONFIG_WINLIST */
/* #undef CONFIG_TASKBAR */
/* #undef CONFIG_APPLET_MEM_STATUS */
/* #undef CONFIG_ADDRESSBAR */
/* #undef CONFIG_TRAY */
/* #undef CONFIG_APPLET_MAILBOX */
/* #undef CONFIG_APPLET_CPU_STATUS */
/* #undef CONFIG_APPLET_NET_STATUS */
/* #undef CONFIG_APPLET_CLOCK */
/* #undef CONFIG_APPLET_APM */
/* #undef CONFIG_WINMENU */

#define WMSPEC_HINTS
#define GNOME1_HINTS
/* #undef DEBUG */


#define HAVE_WORDEXP


#endif // __CONFIG_H__
